apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: maven
      image: maven:3.9.4-eclipse-temurin-17
      imagePullPolicy: IfNotPresent
      command: ['cat']
      tty: true
      volumeMounts:
        - name: m2-cache
          mountPath: /root/.m2
    - name: kubectl
      image: alpine/k8s:1.27.3
      imagePullPolicy: IfNotPresent
      command: ['cat']
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: jenkins-maven-cache-pvc
